# Load in NumPy

In [1]:
import numpy as np

# The Basics

In [56]:
a = np.array([1, 2, 3], 'int16')
print(a)

[1 2 3]


In [4]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get Dimension
print(a.ndim)

1


In [11]:
# Get Shape
a.shape
b.shape

(2, 3)

In [18]:
# Get type
print(a.dtype)
print(b.dtype)

int64
float64


In [23]:
# Get size
a.itemsize 
# = 2 bytes - int16
# = 4 bytes - int32
# = 8 bytes - int64

2

In [28]:
# Get total size
print(a.size) # số phần tử
print(a.size * a.itemsize) # tổng bộ nhớ lưu trữ


3
6


In [31]:
# Get total size (cách 2)
print(a.nbytes) # = 6 bytes = 2 bytes * 3

6


# Accessing/Changing specific elements, rows, columns, etc

In [75]:
 a = np.arange(1, 15).reshape(2, -1)
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [45]:
# Get a specific element [r, c]
print(a[1, -2])
print(a[1, 5])

13
13


In [52]:
# Get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [54]:
# Get a specific column
print(a[:,5])

[ 6 13]


In [55]:
# Getting a little more fancy [start:end:step]
print(a[0, 1:6:2])

[2 4 6]


In [63]:
a[1, 5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [65]:
a[:, 2] = 999
a

array([[  1,   2, 999,   4,   5,   6,   7],
       [  8,   9, 999,  11,  12,  20,  14]])

## 3-d example

In [79]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [86]:
b[:, 1, :]

array([[3, 4],
       [7, 8]])

# Initializing Different Types of Arrays

In [93]:
np.zeros((4, 2, 2), dtype='int32')

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]], dtype=int32)

In [96]:
np.full(shape=(2, 2), fill_value=99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [103]:
# Any other number (full_like)
print('`a` array:')
print(a)
print('------')
print('full() with `a`shape')
np.full(a.shape, 4)

`a` array:
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
------
full() with `a`shape


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [105]:
# Random decimal numbers
np.random.rand(2, 3)

array([[0.64250975, 0.88765154, 0.63941981],
       [0.31259949, 0.15553394, 0.18870237]])

In [108]:
np.random.random(size=a.shape) # tương tự trên nhưng truyền vào shape

array([[0.71073232, 0.36801877, 0.05998191, 0.95439617, 0.68531183,
        0.43432929, 0.26872005],
       [0.93783535, 0.09304785, 0.53405909, 0.63869401, 0.65351419,
        0.79716821, 0.03155594]])

In [111]:
np.random.randint(4, 8, size=(3, 3))

array([[4, 4, 6],
       [5, 5, 6],
       [7, 5, 7]])

In [115]:
np.identity(5) # ma trận đơn vị

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [120]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
r2 = np.repeat(arr, 3, axis=1)
print(r1)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [125]:
output = np.ones((5, 5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Mathematics

In [128]:
a = np.arange(1, 5)
print(a)

[1 2 3 4]


In [129]:
a + 2

array([3, 4, 5, 6])

In [131]:
a - 2

array([-1,  0,  1,  2])

In [132]:
a * 2

array([2, 4, 6, 8])

In [133]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [134]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [135]:
a ** 2

array([ 1,  4,  9, 16])

In [136]:
np.power(a, 2)

array([ 1,  4,  9, 16])

In [139]:
# Take the sin
print('sin', np.sin(a))
print('cos', np.cos(a))
print('tan', np.tan(a))

sin [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
cos [ 0.54030231 -0.41614684 -0.9899925  -0.65364362]
tan [ 1.55740772 -2.18503986 -0.14254654  1.15782128]


For a lot more [NumPy Reference: routines.math.html](https://docs.scipy.org/doc/numpy/reference/routines.math.html)

# Linear Algebra

In [144]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)

In [150]:
print(a)
print('----')
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
----
[[2 2]
 [2 2]
 [2 2]]


In [151]:
a @ b

array([[6., 6.],
       [6., 6.]])

In [152]:
c = np.identity(3)
np.linalg.det(c)

1.0

For a lot more [NumPy Reference: routines.math.html](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

- Determinant
- Trace
- Singular
- Eigenvalue
- Eigenvector
- ...

# Boolean Masking and Advanced Indexing

In [160]:
a =np.random.randint(100, size=(3, 4))
a

array([[41, 20, 31, 34],
       [21, 38, 98, 69],
       [57, 59,  4, 98]])

In [162]:
a[a < 50]

array([41, 20, 31, 34, 21, 38,  4])

In [165]:
~(a < 50) # not

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True, False,  True]])

In [167]:
a[~(a < 50)]

array([98, 69, 57, 59, 98])